### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by RadNotRed** [TaiAurori/custom-timestamps#15]
yeah this doesnt work anymore on powercord probably been said before

**Comment by TaiAurori** [comment]
The plugin still appears to work for me. Have you tried manually unplugging Powercord, running `npm i`, then replugging Powercord? If that doesnt solve it, can you look for some errors in console?

**Comment by RadNotRed** [comment]
Okay that seemed to work, I should've tried that ahead of time.
Thank you for helping!
