### ISSUE TITLE
Plugin doesn't work anymore

### ISSUE THREAD

**Issue by iblowmymind** [TaiAurori/custom-timestamps#19]
Title's pretty self-explanatory, some update broke the plugin.
![image](https://user-images.githubusercontent.com/28228415/145258795-10fb7b71-9419-45ff-a404-66e38d425298.png)

**Comment by TaiAurori** [comment]
![image](https://user-images.githubusercontent.com/31465218/145260233-69f5f2cd-5e51-4c93-846a-90e847a7307a.png)

**Comment by TaiAurori** [comment]
FIXED!!! (i think)

**Comment by iblowmymind** [comment]
seems to be fixed after update & reload, ty!
